- name: Deploy to EC2 via SSH
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: 3.123.1.42
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    script: |
      echo "Connected to EC2 successfully "

      mkdir -p devops-docker-app
      cd devops-docker-app

      if [ ! -d ".git" ]; then
        git clone https://github.com/Ugomichy/devops-docker-app.git .
      else
        git pull origin main
      fi

      docker stop my-app || true
      docker rm my-app || true

      docker build -t my-app .
      docker run -d -p 80:80 --name my-app my-app

      echo "Deployment complete "
